### PR TITLE
Add more profile data

### PR DESCRIPTION
**Pull request by picsoung**
New fields are available in the `/me` response, let's add them to the profile.

thank you @anabellaspinelli for creating and maintaining this library🙏

### CODE REVIEW

**Comment by anabellaspinelli** [comment]
Hey @picsoung :D Thank you for keeping it updated too! :D 

Would you mind adding these fields to the profile.test.js file (and it's corresponding fixture)? Just so that everything stays in sync 🙏🏻

**Comment by picsoung** [comment]
good call! 
just added to both the test file and the fixture 😃

**Review by anabellaspinelli — APPROVED** [review]

**Comment by anabellaspinelli** [comment]
@picsoung I'm not 100% sure that the CI is working, please check if the release was generated correctly 🙏🏻

**Comment by anabellaspinelli** [comment]
Actually it's almost certainly not working haha. I can look into it, it seems the integration with Travis is broken

**Pull request merged**
